; LANG_ENG.INI FILE
; File design by Nyerguds
;
; When placed in the C&C folder or inside a mixfile of the name
; LANG_???.MIX, where ??? is the 3-letter code used for this language,
; this file will add the language specified in the filename.
; For example, lang_xxx.mix will allow you to change the conquer.ini
; Language setting to "Language=XXX"
;
; The game will then read this file and replace all appropriate
; strings in the game's internal settings before loading its files.
; Normally, these strings & files should be enough for a complete
; translation.
;
; Note that partial language packs are possible; if your language pack
; contains no EVA or unit sounds, you can just leave those out, and
; they will be filled in with defaults.
;
; Also note that while normally, leaving defaults reverts to the English
; values, this does makes a language pack susceptible to overriding its
; base settings with the BaseLanguage option. If you want the language pack
; to be 100% fixed, it is advised to simply copy all values.

[Language]
; Language-specific name and briefing tag for missions. Only the official
; extra languages (Ger & Fre) use this, though it is advised to add it to
; allow custom language support in fan missions.

MisNametag=Name
MisBrieftag=Briefing

; strings file extension (will become "conquer.eng")
StringsExt=eng

; Mission briefings & names file
Brieffile=mission.ini

; movies addon folder if LangPath is activated in conquer.ini
cddir=eng

; title screens
; Lo  = 640x400
; Med = 800x600
; Hi  = 1024x768
PCXTitleLo=htitle.pcx
PCXTitleMed=mtitle.pcx
PCXTitleHi=xtitle.pcx

; mix archives
MIXSpeech=speech.mix
MIXTalk=talkeng.mix

; for icons: dese/temp/wint/snowicnh.mix
MIXIcnh=icnh.mix

; sidebar SHPs: actual names have an "H" at the start of the filename.
; Leave that off here: the game adds it automatically when loading the files.
SHPPips=pips.shp
SHPRepair=repair.shp
SHPSell=sell.shp
SHPMap=map.shp

; fonts
FNTGrad6=grad6fnt.fnt
FNT12green=12green.fnt
FNT12grngrd=12grngrd.fnt
FNT8fat=8fat.fnt
FNTVcr=vcr.fnt

; multiplayer score WSA animation (no reliable WSA convertor yet, so only for the official languages)
WSAMulScore=mltsceng.wsa

; "Coming Attraction" screen
CPSAttract=attrceng.cps
