; translation done by Zenix
[Language]
MisNametag=Namespa
MisBrieftag=Briefspa
StringsExt=spa
CDDir=spa
Brieffile=miss_spa.ini
MIXSpeech=speecspa.mix
MIXTalk=talkspa.mix
MIXIcnh=ispa.mix
SHPPips=pipsspa.shp
SHPRepair=reprspa.shp
SHPSell=sellspa.shp
SHPMap=mapspa.shp