[GenericWindow]
DrawMode=Stretched
BackgroundTexture=optionsbg.png
DrawBorders=false

[CnCNetLobby]
DrawMode=Stretched
BackgroundTexture=optionsbg.png
DrawBorders=false
;Size=1220,768

[OptionsWindow]
DrawBorders=false

[HotkeyConfigurationWindow]
DrawMode=Stretched
BackgroundTexture=optionsbg.png
DrawBorders=false

[panelGameStatistics]
DrawMode=Stretched
BackgroundTexture=optionsbg.png

[panelTotalStatistics]
DrawMode=Stretched
BackgroundTexture=optionsbg.png

[ExtraControls]
0=gwtdcl:XNAExtraPanel
1=gwtdcr:XNAExtraPanel
2=box2:XNAExtraPanel
3=box1:XNAExtraPanel

[box1]
DrawMode=Stretched	;Tiled
BackgroundTexture=optionsbg.png
Location=-12,-10
FillWidth=-12
FillHeight=0	;-5	;-10
DrawBorders=false

[box2]
Location=-11,-9
FillWidth=-11
FillHeight=1	;-4	;-9
DrawBorders=true
BorderColor=168,168,168

[gwtdcl]
Location=-7,-6
BackgroundTexture=tdc1l.png
;Size=20,17

[gwtdcr]
Location=0,-6
BackgroundTexture=tdc1r.png
;Size=20,17
DistanceFromRightBorder=-7

[SkirmishLobby]
$Width=RESOLUTION_WIDTH - 40  ; Defines the width of the window
$Height=RESOLUTION_HEIGHT - 34 ; Defines the height of the window
DrawBorders=false

[$ExtraControls]
$CCbg=Background:XNAPanel
$CCgbrdrL=BorderGreyLeft:XNAPanel
$CCgbrdrR=BorderGreyRight:XNAPanel
$CCgbrdrT=BorderGreyTop:XNAPanel
$CCgbrdrB=BorderGreyBottom:XNAPanel
$CCbbrdrL=BorderBlackLeft:XNAPanel
$CCbbrdrR=BorderBlackRight:XNAPanel
$CCbbrdrT=BorderBlackTop:XNAPanel
$CCbbrdrB=BorderBlackBottom:XNAPanel
$CCtdcL=TDCornerLeft:XNAPanel
$CCtdcR=TDCornerRight:XNAPanel

[Background]
SolidColorBackgroundTexture=0,0,0
DrawBorders=false
$Width=getWidth($ParentControl)
$Height=getHeight($ParentControl) + 10
$X=0
$Y=-10
DrawOrder=-2000
UpdateOrder=-2000

[TDCornerLeft]
BackgroundTexture=tdc1l.png
$Width=20
$Height=17
DrawBorders=false
$X=3
$Y=-8

[TDCornerRight]
BackgroundTexture=tdc1r.png
$Width=getWidth(TDCornerLeft)
$Height=getHeight(TDCornerLeft)
DrawBorders=false
$X=getWidth($ParentControl) - getWidth($Self) - 3
$Y=-8

[BorderGreyLeft]
SolidColorBackgroundTexture=168,168,168
$Width=1
$Height=getHeight($ParentControl) + 12
DrawBorders=false
$X=-1
$Y=-11

[BorderGreyRight]
SolidColorBackgroundTexture=168,168,168
$Width=1
$Height=getHeight($ParentControl) + 12
DrawBorders=false
$X=getWidth($ParentControl)
$Y=-11

[BorderGreyTop]
SolidColorBackgroundTexture=168,168,168
$Width=getWidth($ParentControl) + 2
$Height=1
DrawBorders=false
$X=-1
$Y=-11

[BorderGreyBottom]
SolidColorBackgroundTexture=168,168,168
$Width=getWidth($ParentControl) + 2
$Height=1
DrawBorders=false
$X=-1
$Y=getHeight($ParentControl)

[BorderBlackLeft]
SolidColorBackgroundTexture=0,0,0
$Width=1
$Height=getHeight($ParentControl) + 14
DrawBorders=false
$X=-2
$Y=-12

[BorderBlackRight]
SolidColorBackgroundTexture=0,0,0
$Width=1
$Height=getHeight($ParentControl) + 14
DrawBorders=false
$X=getWidth($ParentControl) + 1
$Y=-12

[BorderBlackTop]
SolidColorBackgroundTexture=0,0,0
$Width=getWidth($ParentControl) + 4
$Height=1
DrawBorders=false
$X=-2
$Y=-12

[BorderBlackBottom]
SolidColorBackgroundTexture=0,0,0
$Width=getWidth($ParentControl) + 4
$Height=1
DrawBorders=false
$X=-2
$Y=getHeight($ParentControl) + 1
