;;
;; RULES.INI
;;
;
; You expected awesome text-based modding settings here? Tough luck.
; I only split this because it became a mess in conquer.ini, and because many
; of these options cause desync errors in Multiplayer. So change these settings
; at your own risk.
;
; -Nyerguds

[General]
; --== User interface options ==--
TrueNames=No        ; Show true names for civilians and civilian buildings
TreeTarget=No       ; Show attack cursor on trees (shows on invincible ones too)
SafeScrolling=No    ; Disable scrolling up when on the options or sidebar button
BetaSounds=No       ; Use the beta sounds from ZOUNDS.MIX
NoEgoScreen=No      ; Don't show the score screen after winning a mission
RepeatBriefVid=Yes  ; Replay the briefing video when restarting a mission
; --== Game setup options ==--
LANPlayers=6        ; Set number of LAN players
ParanoidAI=No       ; AI players in LAN/Skirmish will not trust each other
CustomBuildlevel=Yes; In campaign, read buildlevel setting from the mission file
; --== Game behaviour options ==--
WheeledRotation=No  ; Makes wheeled vehicles not turn on the spot like tanks
SeparateHelipad=No  ; Build helipads without helicopters, for only $300
MCVUndeploy=No      ; Construction yard undeploys to MCV when you sell it.
NoBibs=No           ; Disable concrete foundations under buildings
CombatIQ=No         ; Units scatter when attacked (also applies to tanks)
TiberiumOverrun=No  ; Should make tiberium grow faster, but it doesn't work,
                    ; and instead stops all spawning of tiberium on new cells.
Funpark=false       ; Enable hidden dinosaur missions mode (OBSOLETE)
; ===Unknown options===
Combat=No           ; unknown

[Music]
MainMenuTheme=MAP1
GDIMapTheme=MAP1
NodMapTheme=NOD_MAP1
GDIScoreTheme=WIN1
NodScoreTheme=NOD_WIN1
MultiplayerScoreTheme=WIN1
; score themes played on the score screen after the last mission
GDICreditsTheme=OUTTAKES
NodCreditsTheme=OUTTAKES
; default start theme for missions:
DefaultTheme=AOI

